### ISSUE TITLE
Problems with the installation of a Docker in the VM

### ISSUE THREAD

**Issue by Almor21** [jdposada/oop_202201#10]
I have a problem with the installation of Docker inside the VM when I try to execute the command to install it `sudo apt-get install docker-ce docker-ce-cli containerd.io`. I do not know if I am executing the command wrong or it is a problem external to me.

<img width="610" alt="image" src="https://user-images.githubusercontent.com/98895136/154400843-0403e748-be8a-4e4a-82e0-72fc159b96c9.png">

**Comment by jdposada** [comment]
Hi @Almor21 ,

This is likely before the repositories needed to pull the correct packages were not added correctly. Be sure to follow the instructions, in particular the commands below. Those are responsible for updating the package list within Ubuntu. 

```
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

**Comment by Almor21** [comment]
it already worked. With that, I managed to do that and the other steps, thank you very much.
