### ISSUE TITLE
Problem with UML diagram in Visual Studio Code

### ISSUE THREAD

**Issue by EmilyRoldan** [jdposada/oop_202201#12]
When I trying to click in preview nothing can be seen and in the extension appear a warning saying "Write EPIPE". But when I try the same thing in the container, it's work fine. 
![Cap2](https://user-images.githubusercontent.com/98895093/154707612-915a0f9b-606d-4f03-8bdf-dad37bb3db8b.png)
![writeEPIPE](https://user-images.githubusercontent.com/98895093/154708209-e69bbcf8-e040-4ce5-8317-34868537efca.png)
![Cap1](https://user-images.githubusercontent.com/98895093/154707621-d4816106-d6f9-4123-a7ec-99d111b8d3ef.png)

**Comment by jdposada** [comment]
Hi @EmilyRoldan ,

It looks like good behavior since the Docker image was created to ease the process of configuring an environment. As long as it is running within the Docker environment, everything is ok.
