### ISSUE TITLE
Verification of last step for Docker in VM

### ISSUE THREAD

**Issue by EdgarGXI** [jdposada/oop_202201#13]
Teacher, I just wanted to verify that the commands of the last steps were executed correctly, due to they didn't return a message like the other commands

![image](https://user-images.githubusercontent.com/98917634/154820865-11de94b5-b0b6-46e1-b3bb-2920ded3059f.png)

**Comment by jdposada** [comment]
hi @EdgarGXI ,

Everything looks fine. I assume those commands were run on the Azure VM.
