### ISSUE TITLE
Import error on Mamplotlib

### ISSUE THREAD

**Issue by sebdavid3** [jdposada/oop_202201#15]
When I ran the cells appear this error on my interactive tab 
![image](https://user-images.githubusercontent.com/98895197/155244006-d21ce28e-cb2f-479b-b5fa-293e92d5f754.png)
![image](https://user-images.githubusercontent.com/98895197/155244037-6690fd15-0997-43b7-81f3-2fdb84d499f8.png)

**Comment by jdposada** [comment]
hi @sebdavid3 ,

Thank you for posting. Be sure to select the Python kernel with version 3.9. Here you have some [instructions](https://code.visualstudio.com/docs/python/environments#_manually-specify-an-interpreter) on how to do that.

**Comment by sebdavid3** [comment]
Thanks for the help!
![image](https://user-images.githubusercontent.com/98895197/155401948-d3db4439-cfb1-4311-9ad5-4aa6205b58fd.png)

And another mistake that I was doing was running vscode outside of the docker container
