### ISSUE TITLE
Problem opening container into VM

### ISSUE THREAD

**Issue by lellerena** [jdposada/oop_202201#16]
I am having troubles to opening the container into the virtual machine. this is that it "stops"( does not get to move any more) 
![image](https://user-images.githubusercontent.com/69991957/156387718-79f60310-3e4a-4b7f-a6fd-38cc57f0b5bd.png)

**Comment by jdposada** [comment]
Dear @joaco-valenverguen ,

Unfortunately there is not enough info to actually know what may be happenning to you.  I am closing this issue with the hope the issue goes away by itself in your laptop.

Thank you for posting.
