### ISSUE TITLE
Docker problem

### ISSUE THREAD

**Issue by OmarCifuentes** [jdposada/oop_202201#2]
I use Windows and when I open docker, I get this warning and I can't do anything.

![image](https://user-images.githubusercontent.com/79709996/153438339-0b4a7f49-64f0-4d20-be49-873ac3badad4.png)

**Comment by jdposada** [comment]
Dear @OmarCifuentes ,

Have you followed the instructions on the link provided in the message? 

https://aka.ms/wsl2kernel

If yes, did you have an issue with a particular step?

Thanks for posting
