### ISSUE TITLE
Number of cores and size of RAM memory

### ISSUE THREAD

**Issue by yitzhakp** [jdposada/oop_202201#3]
Hi,
I was trying to create the virtual machine, but I get an error when I choose the characteristics specified in the instructions (1 Core and 4 GB RAM). Nevertheless, when I pick another option with different dimensions  (2 Cores and 8 GB RAM) and I do not have any problem to create it. So I do not know if I should create the second option or if I might do something else to be able to create the first one. Here I let some images for you to see what I'm talking about.

![1C4RAM](https://user-images.githubusercontent.com/98917559/153518421-ccaf1ff5-05e1-44af-8c61-d60233647ee3.png)
![2C8RAM](https://user-images.githubusercontent.com/98917559/153518422-0d89fcd9-c5b8-4a6e-b24c-db044d92b9f4.png)

**Comment by jdposada** [comment]
hi @yitzhakp ,

You should select a `Standard_B2s` is has 2vcpus nad 4GiB memory. I will update the README to reflect this.

Thank you for posting the issue
