### ISSUE TITLE
Confirm the correct installation

### ISSUE THREAD

**Issue by sebastianpadilla02** [jdposada/oop_202201#4]
Really, this issue is to confirm if everything is done correctly, I appreciate any suggestion. Thanks
![image](https://user-images.githubusercontent.com/98917806/153732709-ae498fac-1718-4bb9-9cb0-cf5c6413b638.png)
![image](https://user-images.githubusercontent.com/98917806/153732810-1faa19aa-64ca-4ff6-a89a-a38aa60e4348.png)

**Comment by jdposada** [comment]
Hi @sebastianpadilla02 ,

It seems that everything is fine for your local installation. Keep it up.
