### ISSUE TITLE
Error in VM installation process

### ISSUE THREAD

**Issue by Jandres02** [jdposada/oop_202201#5]
When I try to connect to the VM I get this error
Powershell says "permission denied".
![image](https://user-images.githubusercontent.com/98895127/153766872-7f868df0-258d-49c9-8511-851f05bbf75f.png)

**Comment by jdposada** [comment]
Hi @Jandres02,

If you generated a file to connect to the VM, the file is in a location where you need more permissions. If you start PowerShell with admin privileges the problem may go away. To do that follow the instructions [here](https://docs.microsoft.com/en-us/powershell/scripting/windows-powershell/starting-windows-powershell?view=powershell-7.2#with-administrative-privileges-run-as-administrator)

**A better option** is that you specify a username and password to connect to the VM at creation time. You should have a menu like the one in the figure below and in that part, you can specify a good username and password.

![Screenshot from 2022-02-14 09-50-22](https://user-images.githubusercontent.com/11167042/153886845-147f0efc-b17c-4255-9fbb-0d75b7c4df09.png)

Thank you for posting and let me know how it goes

**Comment by ErSantis** [comment]
Hello teacher.
I have the same problem and i don't know how fixed it. I try run powershell with admin privileges but it doesn't work.
![image](https://user-images.githubusercontent.com/93928718/154184341-bccd4b00-c474-4b50-95c1-68ab9b3665e1.png)

**Comment by LuisangelParra** [comment]
You need to check the location of the .pem file on your local machine, cause that file has the access key for the ssh tunnel. 
You can go to file browser and right click on file, and go to the properties of file and copy the location.
Then your should type something like "ssh -i C:\Users\perfil\Descargas\prueba.pem azureuser@ipVM" in your terminal, so if you did not have any other error before, yo can conect with your VM
