### ISSUE TITLE
Error in repository installation process

### ISSUE THREAD

**Issue by sebdavid3** [jdposada/oop_202201#6]
When I cloned the repository appear this error on Visual Studio 

![image](https://user-images.githubusercontent.com/98895197/153875719-187b12ef-3c99-49fd-8857-83bfcf50abd2.png)
![image](https://user-images.githubusercontent.com/98895197/153875767-3bb921bc-f25b-4320-9fe4-44b182babe7d.png)
![image](https://user-images.githubusercontent.com/98895197/153875798-4d088425-addb-49bb-bdbc-029759778543.png)

**Comment by jdposada** [comment]
Hi @sebdavid3 ,

It seems that besides the error shown in red you were actually able to establish a connection and run the container. Please run the file `src/hello_world.py` to confirm that you can run python code inside the container

**Comment by sebdavid3** [comment]
Python is running ok
![image](https://user-images.githubusercontent.com/98895197/154520001-04ddc18a-5bc9-4832-a295-57814b7afb03.png)

Thanks for help
